units/systemd-fsck@.service.in
Informational fsck messages are currently printed to the console,
preventing silent boot.
Upstream commit 66f2ff06ca4ee5ea686b884e2923a31832ad8fe4 changes
this behaviour (I think) - at least I can't see how regular fsck
messages would end up on the console under the new fsckd setup.
So it should be OK to consider this patch already merged upstream.
[endlessm/eos-shell#2109]
=> systemd-fsck@: Don't output to console

src/core/main.c, src/core/manager.c, src/fsck/fsck.c, src/shared/util.c, src/shared/util.h
Even if plymouth is running, it might have not displayed the splash yet,
so we'll see a few lines on fbcon when we should have otherwise had
nothing.
Plymouth integration was added to systemd in commit
6faa11140bf776cdaeb8d22d01816e6e48296971. That same day, Plymouth got
systemd integration [0]. As such, the Plymouth integration has always
been obsolete, and was probably only for older Plymouth's. But I can't
imagine anybody running a Plymouth from 2011 with a systemd from 2015.
Remove the Plymouth/systemd integration, and let Plymouth's code tell
systemd to print the details.
[0] http://cgit.freedesktop.org/plymouth/commit/?id=537c16422cd49f1beeaab1ad39846a00018faec1
Signed-off-by: Jasper St. Pierre <jstpierre@mecheye.net>
https://github.com/endlessm/eos-shell/issues/2109
=> core: Remove explicit Plymouth integration

debian/rules, debian/systemd.postinst, debian/systemd.preinst
Disable networkd: not needed here, we use NetworkManager
Disable resolved: only used by networkd at this time
Disable timesyncd: sounds perfect for Endless, but lets wait for it
to mature first, before we replace ntp. Searching around, there are many
bug reports for this. There are several important-looking fixes that only
went in after v215. It only seems to integrate well with networkd; ntp may
do a better job of watching network connectivity here (need to
check/compare).
[endlessm/eos-shell#4900]
=> Disable resolved, networkd, timesyncd

tmpfiles.d/systemd.conf
As we're building without networkd support, we don't have this
user account.
Comment out these entries, to solve a tmpfiles.d error during boot,
which may also be preventing other tmpfiles.d entries from activating.
[endlessm/eos-shell#4900]
=> tmpfiles.d: disable systemd-networkd entries

Makefile.am, src/shared/sleep-config.c, src/shared/sleep-products.conf
The idea behind here is that we would check, whenever someone asked
logind whether CanSuspend, CanHibernate or CanHybridSleep:
1. Return false if the current machine's product name is blacklisted.
2. Return false if the current machine's product name is not a laptop
(does not have a battery) AND is not explicitly whitelisted.
3. Fallback to the default logic if neither (1) nor (2) apply.
The blacklist and whitelist database would be stored via a configuration
file in /etc/systemd/sleep-products.conf, with its content organized in
sections, listing the product names (as taken from the DMI table) we
want to blacklist or white list for each sleep operation.
Neither this file nor its contents are mandatory, but if it exists, it
would look something like this (not all the sections mandatory …
=> shared: Implement a [white/black]list mechanism for sleep operations

src/locale/localed.c
This reverts commit bb66e74f9472ea5d1ac996a85a259dfcd13fd891. We don't
rely on any of the debian style config files, and this has caused
localed to fail since /etc/default/keyboard is no longer installed from
keyboard-configuration.
[endlessm/eos-shell#5137]
=> Revert "Update localed to use the Debian config files"

debian/50-eos.preset, debian/systemd.install
If systemd does not find a /etc/machine-id file during boot, it will
automatically set all units to a preset enabled or disabled state. If
units aren't matched in any preset files, they'll be enabled.
This file sets the policy for EOS. It simply disables any units that
aren't desired and lets systemd enable the rest (or use the policy in
its own 90-systemd.preset file). In that sense, we want newly installed
units to be enabled and will blacklist any units that are found to be
unwanted.
[endlessm/eos-shell#5134]
=> Add EOS service preset file

debian/rules
This switch is used to ensure that systemd will work on systems where
/bin, /lib and /sbin directories are not symlinks to their /usr
counterparts. On Endless OS this switch causes an error on shutdown.
endlessm/eos-shell#5046
=> Disable 'split-usr' configure option

debian/rules
Make use of systemd's ldconfig service that runs after updates to ensure that the system linker configuration is up to date in case ostree has not deployed the new one.
[endlessm/eos-shell#5364]
=> Run ldconfig after updates

src/readahead/readahead-collect.c
readahead adds a fanotify mark on /, but that doesn't read into /usr
since it's on a separate mount under ostree. Since /usr contains all the
binaries, readahead without it is pretty useless.
If the root to collect is /, add another mark on /usr. Probably this
should check if it's a separate mount but actually the same device, but
this is good enough for now.
[endlessm/eos-shell#5525]
=> readahead: Explicitly add a mark on /usr when collecting /

debian/rules
When a Bluetooth adapter loses power over suspend it is re-probed on
resume and systemd-rfkill will restore the rfkill state from the
previous boot instead of the one right before suspend. This really needs
to be fixed upstream, but for now we're better off disabling
systemd-rfkill.
[endlessm/eos-shell#5598]
=> Disable systemd-rfkill

src/readahead/readahead-collect.c, src/readahead/readahead-common.h, src/readahead/readahead-replay.c, src/readahead/readahead.c, units/systemd-readahead-collect.service.in, units/systemd-readahead-drop.service, units/systemd-readahead-replay.service.in
This allows the root of the ostree deployment to be immutable
while preserving readahead functionality.
[endlessm/eos-shell#5190]
=> Move /.readahead file to /var/.readahead

src/journal/coredump.conf
This will take a lot of resources, so disable it by default until we
have a way to report them.
[endlessm/eos-shell#6048]
=> coredump.conf: default to storing no coredumps

src/shared/conf-parser.c, src/shared/install.c
Allow running preset-all with existing symlinks in /etc, and properly handle escape unit names in unit files.
https://phabricator.endlessm.com/T6363
=> Fix preset/enable

debian/50-eos.preset
The screen package ships this masked service so that the init script is
only run if systemd is not in use. This is breaking preset-all again.
https://phabricator.endlessm.com/T6363
=> Update preset list to handle masked screen-cleanup.service

debian/extra/60-keyboard.hwdb
This fix have been developed and applied on the mainline branch for
master, and cherry-picked for eos2.6. But on this systemd version Debian
overwrites the 60-keyboard.hwdb file with it own version, without the
fixes.
This commit copies the fixes from the eos2.6 branch to the
debian/extra/60-keyboard.hwdb file.
https://phabricator.endlessm.com/T10819
=> debian/extra/60-keyboard.hwdb: Yoga laptops touchpad-toggle keyboard quirk

debian/extra/60-keyboard.hwdb
This fix regress T11082, so we decided to leave the touchpad-toggle hotkey not working on the 2.6 series and fix all the touchpad-related issues on master.
https://phabricator.endlessm.com/T10819
https://phabricator.endlessm.com/T11082
=> Revert touchpad-toggle hotkey fix on 2.6

hwdb/60-keyboard.hwdb
These fixes regress T11082, so we decided to leave the touchpad-toggle hotkey not working on the 2.6 series and fix all the touchpad-related issues on master.
https://phabricator.endlessm.com/T10819
https://phabricator.endlessm.com/T11082
=> Revert touchpad-toggle hotkey fixes on 2.6

debian/control
This is needed otherwise we hit the following problem on dist-upgrade:
Unpacking libsystemd-dev:i386 (229+dev33.2a76238-25bem1) over (215+dev218.bf63765-14bem1) ...
dpkg: error processing archive /var/cache/apt/archives/libsystemd-dev_229+dev33.2a76238-25bem1_i386.deb (--unpack):
trying to overwrite '/usr/share/man/man3/sd_readahead.3.gz', which is also in package systemd 215+dev218.bf63765-14bem1
Errors were encountered while processing:
/var/cache/apt/archives/libsystemd-dev_229+dev33.2a76238-25bem1_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
https://phabricator.endlessm.com/T11440
=> debian/control: libsystemd-dev replaces systemd < 216

debian/control
We compile systemd with --enable-vconsole so we can ship
systemd-vconsole-setup, which uses loadkeys to setup the console
keyboard layout. loadkeys is provided by the kbd package, so we need to
make sure it gets installed.
https://phabricator.endlessm.com/T11575
=> T11575: Add kbd as a dependency

hwdb/60-keyboard.hwdb
Some Yoga 900 models emit 0xbe instead of 0xbf when the touchpad toggle
key is pressed, so we need to map it to KEY_TOUCHPAD_TOGGLE (F21) as
well.
https://phabricator.endlessm.com/T10819
=> [T10819] hwdb: Map 0xbe to F21 on the Yoga 900

src/shared/base-filesystem.c
In Debian's glibc package, ld-linux-x86-64.so.2 symlinks are created in /lib64
and /usr/lib/x86_64-linux-gnu. If /lib is a symlink to usr/lib and /lib64 is a
symlink to usr/lib/x86_64-linux-gnu, these links end up at the same path. In
that case, dpkg may remove them both on upgrade, making the system unusable
because there's no longer a /lib64/ld-linux-x86-64.so.2 linker available.
I'm not sure why you would ever want /lib64 -> usr/lib/x86_64-linux-gnu, but
it's definitely wrong on Endless. There should already be a /lib64 -> usr/lib64
symlink in place, but unfortunately eos-convert-system was missing support to
copy that from the deployment.
https://phabricator.endlessm.com/T11645
=> base-filesystem: Only link /lib64 to /usr/lib64

src/timedate/timedated.c
We do not ship systemd-timesyncd.
https://phabricator.endlessm.com/T11663
=> timedated: Control ntpd instead of systemd-timesyncd

src/core/system.conf
This reverts commit 6d1e1a2650f862b3ef5586550074598c732f3cc1. system.conf no
longer has a DefaultControllers option, and this just results in the warning
"Unknown lvalue 'DefaultControllers' in section 'Manager'" in the journal.
=> Revert "system.conf: enable more cgroups by default"

src/shared/sleep-config.c, src/shared/sleep-products.conf
We will not support these operations, but continue to allow whitelisting
products with the existing configuration file because why not?
https://phabricator.endlessm.com/T13184
=> Disable hibernate and hybrid-sleep by default

src/basic/io-util.c, src/basic/socket-util.c, src/basic/socket-util.h, src/core/socket.c
Previously, we'd simply close and reopen the socket file descriptors. This is
problematic however, as we won't transition through the SOCKET_CHOWN state
then, and thus the file ownership won't be correct for the sockets.
Rework the flushing logic, and actually read any queued data from the sockets
for flushing, and accept any queued messages and disconnect them.
https://phabricator.endlessm.com/T14076
=> core: rework how we flush incoming traffic when a socket unit goes down

rules/78-sound-card.rules
We have a system which has the HDMI audio capability internally,
but pulseaudio is not giving it a very high priority compared
to e.g. USB sound cards.
The sound device appears on the platform bus and it is not
currently tagged with any form factor information.
It seems safe to assume that any sound card that is directly on the
platform bus is of internal form factor, but we must be careful because
udev rules will match all parent devices, not just the immediate parent,
and you will frequently encounter setups such as:
Platform bus -> USB host controller -> USB sound card
In that case, SUBSYSTEMS==platform would match even though we're
clearly working with an external USB sound card.
In order to detect true platform devices here, we rely on the observation
that if any parent devices of …
=> rules: identify internal sound cards on platform bus

hwdb/60-keyboard.hwdb
According to the key code v2.02 from Acer, scancode E0 86 will be
received for airplane mode hotkey.
https://phabricator.endlessm.com/T14825
Signed-off-by: Chris Chiu <chiu@endlessm.com>
=> hwdb: Fix airplane mode key for Acer Aspire models

hwdb/60-keyboard.hwdb
According to the key code v2.02 from Acer, scancode E0 86 will be
received for airplane mode hotkey. Verified on Aspire, TravelMate,
Easynote and Predator.
https://phabricator.endlessm.com/T14825
Signed-off-by: Chris Chiu <chiu@endlessm.com>
=> hwdb: Fix airplane mode key for Acer all series

hwdb/60-keyboard.hwdb
This model emits 0x9a for the microphone mute button above the keyboard,
so let's map it to correct keycode.
https://phabricator.endlessm.com/T16191
=> hwdb: Map 0x8a to F20 on the Acer Travelmate P648-G2-MG

hwdb/60-keyboard.hwdb
Since the power key keycode e076 not only found on Aspire ES1-421,
but also other Aspire/Nitro laptops. Move the keycode mapping for
Acer models.
https://phabricator.endlessm.com/T16475
Signed-off-by: Chris Chiu <chiu@endlessm.com>
=> hwdb: Add power key(button) mapping for Acer models

src/shared/sleep-config.c
In T6455 we disabled suspend by default on all non-laptop systems,
with the option of enabling suspend via a whitelist.
However we never whitelisted any models, and now we work with a number
of All-in-One PCs that have a suspend key on the keyboard that does
not do anything.
Enable suspend on all machine types by default, as long as they
are not blacklisted.
https://phabricator.endlessm.com/T16887
=> Enable suspend by default

debian/rules, debian/systemd.postinst, debian/tests/boot-and-services
Previously, we depended on the "one-time migration" block in postinst to
read /etc/default/tmpfs and enable tmp.mount by copying it into /etc.
This behaviour is inherited from Debian where tmpfs-on-/tmp is not the
default. /etc/default/tmpfs is provided by the initscripts package,
which is no longer a required package and so is not included in the
first phase of debootstrap where the systemd package is installed.
Since we always want /tmp to be a tmpfs in Endless OS, we can just
remove this Debian-specific logic and follow upstream, where tmp.mount
is installed to /lib/systemd/system and symlinked into
/lib/systemd/system/local-fs.target.wants/. Assuming that users have not
modified either /etc/systemd/system/tmp.mount or
the /etc/systemd/system/local-fs.target.wants/tmp.mount symlink,
on …
=> Unconditionally enable tmp.mount

hwdb/60-keyboard.hwdb
Map scancode E0 86 for all Acer brand names/series. Gateway and
Packard Bell all belong to Acer and they need the same mapping.
https://phabricator.endlessm.com/T18710
Signed-off-by: Chris Chiu <chiu@endlessm.com>
=> hwdb: Fix airplane mode key for Acer all brand names/series

hwdb/60-keyboard.hwdb
This model emits 0x8a for the microphone mute button above the keyboard,
so let's map it to correct keycode.
https://phabricator.endlessm.com/T18711
=> hwdb: Map 0x8a to F20 on the Acer Travelmate P648-G3-M

debian/50-eos.preset
This is supposed to only be enabled on certain images, to which
/etc/systemd/system-preset/40-eos-update-server.preset is added at image
build time with:
enable eos-update-server.socket
enable eos-updater-avahi.path
But due to our enabled-unless-proven-guilty behaviour, they were in fact
enabled on all systems.
The daemon actually quits as soon as it is started if its config file
doesn't instruct it to advertise updates, so this is only a boot-time
performance problem, not a correctness problem.
https://phabricator.endlessm.com/T18824
=> eos.preset: disable peer-to-peer updater by default

src/gpt-auto-generator/gpt-auto-generator.c
We don't want to have the ESP automatically mounted on non-EFI systems,
as this has the side-effect of removing the /sysroot/boot -> /boot
bind-mount needed by OSTree systems which don't use a separate boot
partition.
This effectively reverts the change introduced by
commit 7ba25ab5616339a8340117b85cbecd061c52d8cc
Author: Lennart Poettering <lennart@poettering.net>
Date:   Thu Jul 21 11:30:02 2016 +0200
gpt-generator: relax EFI check a bit
Previously, we'd not mount the ESP except on EFI boots, and only when the ESP
used for booting matches the ESP we found.
With this change on non-EFI boots we'll mount a discovered ESP anyway, and on
EFI boots we'll only mount it if it matches the ESP we booted from.
https://phabricator.endlessm.com/T18825
=> gpt-auto-generator: Do not mount the ESP on non-EFI systems

src/rfkill/rfkill.c
This queues rfkill state change events in memory, and if the switch disappears (a delete event comes from `/dev/rfkill` for that switch), the event is removed from the queue. The queue is saved to disk on exit.
This PR also brings a couple fixes to systemd-rfkill and a refactor to make the commit that fixes our problem apply cleanly. After this PR, systemd-rfkill will be on par with upstream's master.
https://phabricator.endlessm.com/T18582
=> [T18582]  rfkill: Delay writes until exit

src/shared/sleep-products.conf
There's a bug on Weibu F3C Mini PCs where suspend breaks WiFi support.
The fix for that (https://phabricator.endlessm.com/T20168) won't be
included in a stable EOS release in time for the next round of
production, so this commit disables suspend on this hardware
temporarily. The effect is that there's no Suspend option in Settings
(gnome-control-center) and pressing the power button prompts the user to
shut down rather than immediately suspending.
https://phabricator.endlessm.com/T20298
=> shared: Disable suspend on Weibu F3C units

src/shared/sleep-products.conf
The config file parser only allows full line comments, so change
sleep-products.conf to comply.
https://phabricator.endlessm.com/T20298
=> shared: Fix comment in sleep-products.conf

meson.build
Meson does not provide GNU triplets [1], as autoconf used to through the
AC_CANONICAL_HOST macro. systemd-readahead uses them to tag packfiles.
If we want to remain compatible with packfiles in the wild, we need to
implement them somehow.
[1] https://github.com/mesonbuild/meson/issues/2077
This defines CANONICAL_HOST with what the old AC_CANONICAL_HOST macro
would return:
- on armhf: "arm-unknown-linux-gnueabihf"
- on amd64: "x86_64-pc-linux-gnu"
It adds a dependency on dpkg-architecture, so it will only work on
Debian-based systems.
https://phabricator.endlessm.com/T21201
=> meson: Calculate GNU triplet

src/shared/dissect-image.c
Filter-out RPMB partitions and boot partitions from MMC devices when
counting partitions enumerated by the kernel.
This complement the previous fixes to the problem reported in
https://github.com/systemd/systemd/issues/5806
https://phabricator.endlessm.com/T21744
=> dissect: Don't count RPMB and boot partitions

src/journal/journald.conf
This also sets the on-disk granularity to about 1 MiB per journal file.
When the maximum storage is used, journald will delete the oldest
journal file and allocate a new one to continue writing. Finer
granularity results in larger journal retention but more-frequent file
deletion and creation.
With these settings, this retains about 20k lines of messages which
roughly corresponds to 40 active hours on a relatively busy system.
For the purposes of classrooms, this would likely span multiple weeks.
NOTE: these changes only apply to the on-disk (persistent) journal and
that only gets used if /var/log/journal exists and is writable. That is
not true as of this writing but will soon be true for machines with
durable (non-MMC/-SD) storage.
https://phabricator.endlessm.com/T21771
=> Set the maximum on-disk joural size to 50 MiB

rules/50-udev-default.rules.in
Debian's patch to have /dev/kvm udev rules defined in a qemu package means we get no permissions set on /dev/kvm in Endless OS. Revert the Debian patch so we get 0666 permissions again, but remove the "kvm" group which is not defined in Endless.
https://phabricator.endlessm.com/T22718
=> T22718: make /dev/kvm 0666

src/core/dbus-execute.c, src/core/manager.h, src/core/mount.c
linux/fs.h sys/mount.h, libmount.h and missing.h all include MS_*
definitions.
To avoid problems, only one of linux/fs.h, sys/mount.h and libmount.h
should be included. And missing.h must be included last.
Without this, building systemd may fail with:
In file included from [...]/libmount/libmount.h:31:0,
from ../systemd-238/src/core/manager.h:23,
from ../systemd-238/src/core/emergency-action.h:37,
from ../systemd-238/src/core/unit.h:34,
from ../systemd-238/src/core/dbus-timer.h:25,
from ../systemd-238/src/core/timer.c:26:
[...]/sys/mount.h:57:2: error: expected identifier before numeric constant
=> core: don't include libmount.h in a header file (#8580)

rules/50-udev-default.rules.in
Arduino devices expose a USB modem interface for communication. We want
these to be accessible by all users in the system. Ideally we would add
all real users to the dialout group, but this is not straightforward on
an OSTree-based system.
https://phabricator.endlessm.com/T21435
=> rules: Set mode 0666 for ttyACM* devices

debian/systemd.postinst
Do not create a systemd-timesync user. During the last rebase I let this
slip through the cracks. Leaving as a fixup so we remember to do it as
part of the commit which disables timesyncd on the next rebase.
https://phabricator.endlessm.com/T23373
=> fixup! Disable timesyncd

debian/udev.postinst
We set /dev/kvm access mode to 0666, so we don't need a kvm user or
group.
https://phabricator.endlessm.com/T23373
=> Do not create kvm group

src/core/namespace.c
This reverts commit 0722b359342d2a9f9e0d453875624387a0ba1be2.
With that commit systemd tried to bind-mount / on /run/systemd/unit-root
before spawning units with PrivateMounts=yes, which now includes udev.
udev is started in the initrd, and bind-mounting / on
/run/systemd/unit-root fails in the EC-100, possibly because of the
u-boot header that is wrapped around the dracut image so u-boot is able
to load it.
Reverting this fix avoids the problem while we try to figure out a
upstream fix.
https://phabricator.endlessm.com/T23609
=> Revert "namespace: always use a root directory when setting up namespace"

src/core/namespace.c
This reverts commit a46face108ecb9108c67717bd0d90e5f36aabeaf.
We have fixed the underlining problem in the EC-100 kernel, so we can
drop this revert.
https://phabricator.endlessm.com/T23609
=> Revert "Revert "namespace: always use a root directory when setting up namespace""

units/systemd-tmpfiles-setup.service.in
systemd-tmpfiles-setup.service needs to be ordered after
systemd-journald.service, so entries in /run/log/journal are already
created when systemd-tmpfiles tries to adjust its permissions.
This is specially problematic for setups using a volatile journal where
the initrd does not ship a machine-id (i.e. OSTree-based systems), where
logs from the initrd will be inaccessible for users in the
systemd-journal group. It also has a side effect of `journalctl --user`
failing with "No journal files were opened due to insufficient
permissions".
https://phabricator.endlessm.com/T23634
=> tmpfiles: Order tmpfiles-setup after journald

hwdb/60-keyboard.hwdb
This is mapped to KEY_DISPLAY_OFF in the kernel, but this key code is
not mapped to any XF86 media key and nothing in userspace handles it.
Let's map it to screenlock instead.
https://phabricator.endlessm.com/T20914
=> hwdb: Map 0x35 to screenlock for Asus WMI hotkeys

hwdb/60-sensor.hwdb
Acer Veriton Z4860G, Z6860G, A890 with the same STM accelerometer
suffer the same problem with Z4660G. Apply the same mount matrix
for them.
https://phabricator.endlessm.com/T24115
=> hwdb: apply same accel mount setting for more Acer AIO Veriton series

hwdb/60-keyboard.hwdb
This reverts commit cc13eca21baf60224d1930201ebf992a07f0ff91.
We are now mapping 0x35 to KEY_SCREENLOCK in the kernel.
https://phabricator.endlessm.com/T24298
=> Revert "hwdb: Map scan code 0x35 to screenlock on Asus machines"

debian/extra/pam.d/systemd-user
Apply a version of the change in 
https://github.com/systemd/systemd/commit/ab79099d so that the user
keyring is available in systemd-user sessions, which allows keys to be
configured for accessing encrypted filesystems. See
https://github.com/google/fscrypt/issues/100 and
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1754270 for more
details.
https://phabricator.endlessm.com/T27032
=> pam.d/systemd-user: add pam_keyinit to link session and user keyrings

src/boot/efi/boot.c
ostree uses symlinks on the boot filesystem, this isn't great when that
filesystem is vfat, which can't do symlinks. Since the EFI ESP must be
vfat on most implementation, this makes ostree incompaible with sd-boot.
To allow ostree to keep making symlinks, we make a fake symlink that's
just a text file with the name of the file that would be linked to.
https://phabricator.endlessm.com/T27040
=> sd-boot: Read fake symlinks

debian/control
For PAYG, the systemd-boot EFI loader needs to be signed, and this will
be part of a systemd-signed package. Ensure that only systemd or
systemd-signed can be installed by adding Conflicts and Replaces on that
package. The secure boot signer will swap these to systemd when creating
the systemd-signed package.
https://phabricator.endlessm.com/T27442
=> Ensure only systemd or systemd-signed can be installed

src/boot/efi/stub.c
We want a combination of the built in parameters from the efi image
and safe parameters from the loader config.
https://phabricator.endlessm.com/T27591
=> sd-boot: Combine command line parameters for payg

debian/control, debian/systemd-boot.install
Move systemd-boot into a separate package so it can be signed and replace the unsigned version without affecting the main systemd package. Replacing the systemd package would likely run into many problems since it has many reverse dependencies and it's pulled into the OS early since it's priority important.
https://phabricator.endlessm.com/T27442
=> Split out systemd-boot for signing

src/boot/efi/stub.c
If secure boot is off it could be useful to pass arbitrary parameters
for debug purposes.
https://phabricator.endlessm.com/T27591
=> efi-stub: Allow any kernel parameters when not in secure boot mode

hwdb/60-sensor.hwdb, hwdb/parse_hwdb.py
The lis3lv02d sensor used in many HP laptops is (almost) always intented
primarily for freefall detection / HDD protection and (almost) always
is located in the base of a classic clamshell laptop
Before we had the ACCEL_LOCATION udev property the issues this caused
with screen-rotation were fixed by applying a mount-matrix which
translates base-coordinates to display-coordinates assuming the display
is at an angle of exact 90 degrees to the base (swap Y and Z axis).
The comment calls this translate "from "can play neverball" to
"matches Windows 8 orientation"" but what it really does is translate
base accel-axis to display accel-axis. Thus allows rotating the screen
if you put the laptop on its side, but no-one normally does that with
a 2Kg clamshell laptop.
The obviously correct thing to …
=> hwdb: Mark lis3lv02d sensors in HP laptops as being in the base

src/boot/efi/boot.c, src/boot/efi/meson.build, src/boot/efi/ms_test.sh
We've encountered firmware that searches the boot loader for the string
"Microsoft" and uses that to determine which ACPI table to deliver to
the kernel.
Make sure that string is present so these computers do the right thing.
https://phabricator.endlessm.com/T27753
=> sd-boot: Work around odd behaviour in some firmware

src/login/logind-user.c
Interestingly, elect_display_compare() already ordered "user" sessions
before "greeter" sessions, though nothing other than "user" sessions
where ever considered anyway.
Fixes: #12399
(cherry picked from commit a2dcb1d78737d3daa301ee63fbdd02837acb71a8)
Signed-off-by: Robert McQueen <rob@endlessm.com>
https://phabricator.endlessm.com/T28186
=> logind: consider "greeter" sessions suitable as "display" sessions of a user

hwdb.d/60-keyboard.hwdb
On the WeiHeng P325J laptop, Fn+F2 sends LeftWindow (0xe0 0x5b) +
LeftCtrl (0x1d) + F24 (0x76). Add a quirk to remap the 0x76 to F21 which
toggles the touchpad. The Ctrl + Win part is handled in userspace, e.g
by gnome-settings-daemon here:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/commit/f545950fe
This is analogous to what was done for the T-bao hardware here:
https://github.com/systemd/systemd/commit/d4a5df521d
(cherry picked from commit 68697cdd1274fe64ec57ac3a01f645ee821d6238)
=> hwdb: Fix touchpad toggle on WeiHeng P325J

src/shared/sleep-products.conf
We detected a regression here where USB input devices do not work after
resuming from suspend. Let's disable suspend while we investigate a more
permanent solution, and on the stable branch (currently eos3.7) as well.
The Mission One is based on the Gigabyte Brix GB-BXBT-2807, so we are
disabling both product names here.
https://phabricator.endlessm.com/T29497
=> sleep-products: Disable suspend on the Mission One

src/gpt-auto-generator/gpt-auto-generator.c
On PAYG images we mount the ESP to /boot and install the boot loader
configuration and entries there, as this is a requirement of
sysytemd-boot. The GPT auto generator finds the ESP and generates an
automount unit for it at /boot in a way that makes it only accessible
and readable by root. OSTree needs to read the contents of
/boot/loader/entries for non-root `ostree admin status`, and probably
other similar actions.
This commit changes the umask used in boot.mount to allow for group and
others to read files and access directories in the ESP mounted to /boot.
https://phabricator.endlessm.com/T29520
=> [Endless] gpt-auto-generator: Allow non-root to read the ESP in /boot

hwdb.d/60-keyboard.hwdb
Acer defines Fn+F9/10 as keyboard brightness down/up on Predator PH
315-52 laptop. So, add the quirk to correct key mappings.
https://phabricator.endlessm.com/T29638
=> hwdb: Fix kbd brightness keys on Acer Predator PH 315-52

src/shared/sleep-products.conf
Resuming from suspend does not work on the ECS EF20EA using recent
master or eos3.8 ostrees, so disable suspend as a short-term fix.
https://phabricator.endlessm.com/T29890
=> sleep-products: Disable suspend on ECS EF20EA

rules.d/50-udev-default.rules.in
Fixup for dc223266 to remove another reference to the "kvm" group. Can be squashed on next rebase.
https://phabricator.endlessm.com/T30229
=> fixup! rules: Remove references to the "kvm" group

hwdb.d/60-keyboard.hwdb
Pinebook Pro's display brightness up & down keys do not work until the
keys are mapped to the corresponding codes.
Also, the sleep key is mapped to KEY_POWER code originally. This quirk
maps the sleep key to the KEY_SLEEP code.
This idea comes from the pinebookpro-post-install package [1] of Manjaro
ARM, which is the preloaded OS on Pinebook Pro.
https://phabricator.endlessm.com/T31050
[1]: https://gitlab.manjaro.org/manjaro-arm/packages/community/pinebookpro-post-install/-/commit/7ab1a134ea9d5b55d99de567d1ebee4ebd6f6640
=> hwdb: Fix Pinebook Pro's brightness up/down and sleep keys

units/systemd-timedated.service.in
Part of moving from ntpd to systemd-timesyncd.
See: https://community.endlessos.com/t/xterm-shows-in-3-10/16322/18 for more
This reverts commit 18be2ab3dde77ec57474d3792c2038221e855b6a.
=> Revert "[Endless] timedated: Control ntpd instead of systemd-timesyncd"

man/systemd-time-wait-sync.service.xml, man/systemd-timesyncd.service.xml, man/systemd.special.xml, man/timesyncd.conf.xml, src/basic/special.h, src/core/timer.c, src/timesync/timesyncd-bus.c, src/timesync/timesyncd-conf.c, src/timesync/timesyncd-gperf.gperf, src/timesync/timesyncd-manager.c, src/timesync/timesyncd-manager.h, src/timesync/timesyncd.c, src/timesync/timesyncd.conf.in
Backport https://github.com/systemd/systemd/commit/33e82f3ef3 to periodically save time and keep the clock monotonic on systems without a battery-backed RTC.
This PR also brings other commits to make for clean cherry-picks. Most of those are manpage fixes, but some add a couple of small features and seem nice to have.
https://phabricator.endlessm.com/T32428
=> Backport periodically time saving by systemd-timesyncd

debian/rules, debian/systemd-journal-remote.install, debian/systemd.install
Since the sysuser.d folder does not exists when sysusers is disabled,
drop sysusers related install items.
https://phabricator.endlessm.com/T31589
=> Drop sysusers related files

debian/control
Debian's new systemd (since 251.2-3) places the EFI stub into systemd-boot-efi package. So, going to sign it as systemd-boot-efi-signed to be installed.
https://phabricator.endlessm.com/T33862
=> Ensure only systemd-boot-efi or systemd-boot-efi-signed can be installed

src/boot/efi/boot.c, src/boot/efi/meson.build, src/boot/efi/ms_test.sh
This reverts commit 855dd915b15345ef597515339479aa4c8350b22b.
Drop for ECS EF20EA since EOS 5+
https://phabricator.endlessm.com/T33759
=> Revert "[Endless] sd-boot: Work around odd behaviour in some firmware"

tmpfiles.d/tmp.conf
This reverts commit 97461254ad826ac7a36f6ea7e181c8e65cc6a98f.
Debian's policy is to never clean-up /var/tmp to keep consistency with the SysV init system. Flatpak creates temporary files in /var/tmp during app updates but does not remove them on error, to avoid re-downloading them on a future update attempt, and expects these files to be automatically cleaned-up by the system eventually, according to the site's policy. With this policy in place these files are never removed, wasting the user's storage space.
Revert this commit back to upstream's default policy of cleaning up /tmp every 10 days and /var/tmp every 30 days.
https://phabricator.endlessm.com/T23762
https://phabricator.endlessm.com/T33887
=> Revert "[DEB] Bring tmpfiles.d/tmp.conf in line with Debian defaults"

src/boot/efi/meson.build
Note that -O0 is deliberately filtered out as we have to compile with at least -O1 due to #24202.
Fixes: #24323
(cherry picked from commit 7aa4762ce274a1c9a59902b972fa4fdee1b22715)
This is a backport from upstream that's needed now that meson got updated to 1.0.
=> meson: Fix build with --optimization=plain

src/boot/efi/meson.build, src/gpt-auto-generator/gpt-auto-generator.c
If LoaderDevicePartUUID isn't set because the boot loader doesn't support it,
assume that the ESP partition on the root disk is the booted ESP. This is a
weaker guarantee but likely the same for the vast majority of systems. Allowing
the ESP automount in this case helps break a dependency loop. Existing boot
loaders can be changed to set LoaderDevicePartUUID, but they can't be delivered
to existing systems if the ESP is not mounted.
Upstream: https://github.com/systemd/systemd/pull/26430
https://phabricator.endlessm.com/T29930
This is on top of #163. I sent this upstream, but I doubt it's going to get merged. For Endless I think this makes sense to bootstrap updating EFI programs so that eventually we can have a grub that supports `LoaderDevicePartUUID`.
@wjt pointed out that this …
=> gpt-auto-generator: mount ESP when LoaderDevicePartUUID isn't set

src/boot/efi/boot.c
Fix with the new error handling for new systemd-boot.
https://phabricator.endlessm.com/T35070
=> fixup! [Endless] sd-boot: Read fake symlinks

src/sleep/sleep.conf
This reverts commit 742be08f3badd35fa146c25b61fb23690dd658c1.
Hibernation is availabe only when secure boot is disabled. However, disabled secure boot is not EOS' common case. Let users choose preferred configuration for suspend by themselves. So, revert the downstream modification.
More detail discussion: https://phabricator.endlessm.com/T35070#990597
=> Revert "[Endless] sleep.conf: Disable hibernate and hybrid-sleep by default"
